-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 14:06:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answers` (
  `id` INT NOT NULL,
  `correct` TINYINT NULL,
  `not_correct` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questions_has_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions_has_answers` (
  `questions_id` INT NOT NULL,
  `answers_id` INT NOT NULL,
  PRIMARY KEY (`questions_id`, `answers_id`),
  INDEX `fk_questions_has_answers_answers1_idx` (`answers_id` ASC),
  INDEX `fk_questions_has_answers_questions_idx` (`questions_id` ASC),
  CONSTRAINT `fk_questions_has_answers_questions`
    FOREIGN KEY (`questions_id`)
    REFERENCES `mydb`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_has_answers_answers1`
    FOREIGN KEY (`answers_id`)
    REFERENCES `mydb`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_answers` (
  `users_id` INT NOT NULL,
  `answers_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `answers_id`),
  INDEX `fk_users_has_answers_answers1_idx` (`answers_id` ASC),
  INDEX `fk_users_has_answers_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_answers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_answers_answers1`
    FOREIGN KEY (`answers_id`)
    REFERENCES `mydb`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;